server:
  port: 8080  # Let Spring Boot choose a random port

external:
  officialjokeapi:
    base-url: http://localhost:9090/officialJoke
  chucknorrisapi:
    base-url: http://localhost:9090/chuckNorris
  jokeapi:
    base-url: http://localhost:9090/jokeAPI