name: Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write        # Grants write access to repository contents
  pull-requests: write  # Grants write access to pull requests

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: 'java'  # Specifies Java project
          token: ${{ secrets.GITHUB_TOKEN }}
