name: Release

on:
  push:
    branches:
      - main
    # Optionally, trigger on pull requests if desired

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch all history for Release Please

      # 2. Set up JDK (required for Maven operations if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'  # Update to your project's Java version

      # 3. Configure Git user (necessary for committing changes)
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 4. Install Release Please
      - name: Install Release Please
        run: |
          curl -sS https://raw.githubusercontent.com/googleapis/release-please/master/release-please.sh | bash

      # 5. Run Release Please
      - name: Run Release Please
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
        run: |
          npx release-please release-pr --token $GITHUB_TOKEN
